export const SERVICES = [
  {
    id: 'ocaas',
    num: '01',
    short: 'OCaaS',
    name: 'OpenClaw-as-a-Service',
    icon: '🔧',
    color: '#00f5ff',
    desc: 'Orchestrate and deploy open-source tools as fully managed AI services. Robotic assembly of best-in-class open-source infrastructure — zero overhead, maximum intelligence.',
    theme: 'Industrial AI lab — mechanical precision meets intelligent orchestration.',
    visual: 'claw',
  },
  {
    id: 'saas',
    num: '02',
    short: 'SaaS',
    name: 'SaaS Platform Engineering',
    icon: '☁️',
    color: '#0066ff',
    desc: 'Design, build, and scale cloud-native SaaS products on AI-optimized architecture. Floating platforms, connected dashboards, seamless product ecosystems at enterprise scale.',
    theme: 'Clean, structured product ecosystem built on intelligent cloud foundations.',
    visual: 'cloud',
  },
  {
    id: 'iaas',
    num: '03',
    short: 'IaaS',
    name: 'Infrastructure-as-a-Service',
    icon: '⚙️',
    color: '#7c3aed',
    desc: 'Infinite-scale infrastructure networks with AI-monitored performance, self-healing systems, and proactive threat response. The backbone of modern enterprise digital operations.',
    theme: 'Power, scale, and resilience — the bedrock of your digital operations.',
    visual: 'grid',
  },
  {
    id: 'aaas',
    num: '04',
    short: 'AutoaaS',
    name: 'Automation-as-a-Service',
    icon: '🔄',
    color: '#00ff88',
    desc: 'Intelligent workflow automation that learns, adapts, and optimizes in real time. Flowing data pipelines that never sleep, never fail, and continuously improve with every cycle.',
    theme: 'Motion and efficiency — autonomous systems that evolve continuously.',
    visual: 'flow',
  },
  {
    id: 'dev',
    num: '05',
    short: 'Custom Dev',
    name: 'Custom Development',
    icon: '💻',
    color: '#ff6600',
    desc: 'Transform requirements into living applications. AI-accelerated development with human architects ensuring every line of code is purposeful, scalable, and future-ready.',
    theme: 'Creation and transformation — code that becomes real-world capability.',
    visual: 'code',
  },
  {
    id: 'agentbuild',
    num: '06',
    short: 'Agent Build',
    name: 'AI Agent Building',
    icon: '🤖',
    color: '#ff0080',
    desc: 'Design and deploy custom AI agents tailored to your exact enterprise workflows. Intelligent digital workers that reason, act, and improve autonomously around the clock.',
    theme: 'Intelligence creation — digital minds shaped by your enterprise DNA.',
    visual: 'agent',
  },
  {
    id: 'agentaas',
    num: '07',
    short: 'AgentaaS',
    name: 'AI Agent-as-a-Service',
    icon: '🧩',
    color: '#00ccff',
    desc: 'Plug-and-play marketplace of pre-built AI agents ready for immediate enterprise deployment. Capsule-ready intelligence that integrates in hours, not months.',
    theme: 'Plug-and-play intelligence — ready-deployed AI workforce on demand.',
    visual: 'capsule',
  },
  {
    id: 'legacy',
    num: '08',
    short: 'Legacy AI',
    name: 'AI Integration for Legacy Software',
    icon: '🔗',
    color: '#ffd700',
    desc: 'Upgrade legacy systems with intelligent AI layers without disruption. Transform aging infrastructure into AI-enabled platforms that compete with modern technology stacks.',
    theme: 'Transformation and evolution — your past systems, supercharged for the future.',
    visual: 'upgrade',
  },
  {
    id: 'hr',
    num: '09',
    short: 'HR AI',
    name: 'HR & Staffing Solutions',
    icon: '👥',
    color: '#ff6b9d',
    desc: 'AI-powered talent matching, workforce analytics, and intelligent HR automation. Human networks enhanced by precise AI — connecting the right people at the right time.',
    theme: 'Human + AI synergy — intelligent talent systems for modern organizations.',
    visual: 'network',
  },
  {
    id: 'compliance',
    num: '10',
    short: 'Compliance',
    name: 'Compliance & Business Services',
    icon: '⚖️',
    color: '#64ffda',
    desc: 'AI-driven compliance monitoring, regulatory intelligence, and secure document management. Digital vaults and shield systems protecting your enterprise at every layer.',
    theme: 'Trust and stability — enterprise compliance powered by intelligent automation.',
    visual: 'vault',
  },
  {
    id: 'marketing',
    num: '11',
    short: 'AI Marketing',
    name: 'AI-enabled Digital Marketing',
    icon: '📈',
    color: '#ff4757',
    desc: 'Data-driven marketing intelligence that targets, adapts, and scales campaigns in real time. AI that understands your audience at a depth no human team can replicate alone.',
    theme: 'Expansion and reach — growth engines powered by deep audience intelligence.',
    visual: 'growth',
  },
];

export const CASES = [
  {
    tag: 'IaaS + Automation',
    title: 'Global Fintech Scales to 10M Users',
    desc: 'Deployed IaaS and Automation modules to handle explosive user growth with zero downtime events during the transition period.',
    metrics: [{ v: '340%', l: 'Throughput' }, { v: '99.99%', l: 'Uptime' }],
    color: '#00f5ff',
  },
  {
    tag: 'AI Agent Building',
    title: 'E-commerce Giant Automates Support',
    desc: 'Custom AI agents handle 94% of customer support interactions autonomously, with human escalation for complex edge cases.',
    metrics: [{ v: '94%', l: 'Automation Rate' }, { v: '4.8★', l: 'Customer Rating' }],
    color: '#0066ff',
  },
  {
    tag: 'Legacy AI Integration',
    title: 'Healthcare Provider Modernizes Stack',
    desc: '20-year-old hospital management system upgraded with AI layers, enabling predictive analytics and automated scheduling.',
    metrics: [{ v: '60%', l: 'Admin Time Saved' }, { v: '$2.4M', l: 'Annual Savings' }],
    color: '#7c3aed',
  },
  {
    tag: 'AI Marketing',
    title: 'D2C Brand Triples Revenue in 12 Months',
    desc: 'AI-enabled digital marketing identifies micro-segments and deploys hyper-personalized campaigns at machine speed.',
    metrics: [{ v: '3.1×', l: 'Revenue Growth' }, { v: '41%', l: 'CAC Reduction' }],
    color: '#ff0080',
  },
  {
    tag: 'OCaaS + Custom Dev',
    title: 'Logistics Company Rebuilds Core Platform',
    desc: 'End-to-end platform rebuild using OCaaS orchestration and custom development, cutting operational costs dramatically.',
    metrics: [{ v: '52%', l: 'Cost Reduction' }, { v: '8×', l: 'Deploy Speed' }],
    color: '#00ff88',
  },
  {
    tag: 'HR & Compliance AI',
    title: 'Fortune 500 Transforms HR Operations',
    desc: 'AI-powered talent matching and compliance automation deployed across 12 countries, streamlining global workforce management.',
    metrics: [{ v: '78%', l: 'Hiring Efficiency' }, { v: '100%', l: 'Compliance' }],
    color: '#ffd700',
  },
];

export const JOBS = [
  { title: 'Senior AI Engineer', dept: 'AI CORE', type: 'Full-Time · Remote' },
  { title: 'ML Infrastructure Engineer', dept: 'INFRASTRUCTURE', type: 'Full-Time · Remote' },
  { title: 'AI Agent Architect', dept: 'AGENT PLATFORM', type: 'Full-Time · Hybrid' },
  { title: 'Enterprise Solutions Engineer', dept: 'SOLUTIONS', type: 'Full-Time · Remote' },
  { title: 'Human Oversight Specialist', dept: 'OPERATIONS', type: 'Full-Time · Remote' },
  { title: 'Product Designer — AI Systems', dept: 'DESIGN', type: 'Full-Time · Remote' },
];

export const TIMELINE = [
  { year: '2019', title: 'The Seed Protocol', desc: 'LucenEdge founded with a vision to bridge AI capability and enterprise-grade reliability. First five engineers, one mission.' },
  { year: '2020', title: 'First Module Deployed', desc: 'OCaaS launched to critical acclaim. Open-source orchestration as a managed AI service becomes the foundation of the LucenEdge stack.' },
  { year: '2021', title: 'Automation Core Activated', desc: 'Automation module processes its first 1 million workflows. Human oversight layer formalized into a dedicated ops division.' },
  { year: '2022', title: 'AI Agent Platform Born', desc: 'First generation of AI agents deployed for enterprise clients. Agent-building toolkit opens to select enterprise partners.' },
  { year: '2023', title: 'Full Stack Intelligence', desc: 'Complete 11-module AI stack unified under the LucenEdge Intelligence Platform. 200+ enterprise clients onboarded.' },
  { year: '2025', title: 'Next Frontier', desc: 'Expanding into legacy AI integration and enterprise compliance AI. Building the intelligence stack for the next decade.' },
];
